import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Smartphone, QrCode, CheckCircle } from "lucide-react";

interface InstaPayPaymentProps {
  amount: number;
  orderId?: string;
  onConfirm?: () => void;
}

export function InstaPayPayment({ amount, orderId, onConfirm }: InstaPayPaymentProps) {
  const [qrCodeUrl, setQrCodeUrl] = useState<string>("");

  useEffect(() => {
    // Generate QR code URL using a QR code API
    // In production, this should be generated by backend with actual InstaPay details
    const paymentData = `instapay://pay?amount=${amount}&merchant=CURLYELLIE&ref=${orderId || Date.now()}`;
    const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(paymentData)}`;
    setQrCodeUrl(qrUrl);
  }, [amount, orderId]);

  return (
    <div className="space-y-4">
      <div className="p-4 bg-purple-50 border border-purple-200 rounded-lg">
        <div className="flex items-center gap-2 mb-3">
          <Smartphone className="w-5 h-5 text-purple-600" />
          <span className="font-semibold text-purple-900">InstaPay Payment</span>
        </div>
        
        <div className="space-y-2 text-sm text-purple-700">
          <p className="font-medium">Payment Instructions:</p>
          <ol className="list-decimal list-inside space-y-1 ml-2">
            <li>Open your bank's mobile app</li>
            <li>Select InstaPay from payment options</li>
            <li>Scan the QR code below</li>
            <li>Confirm payment of <span className="font-bold">${amount.toFixed(2)}</span></li>
          </ol>
        </div>
      </div>

      <div className="bg-white border-2 border-purple-300 rounded-lg p-6">
        <div className="flex flex-col items-center">
          <QrCode className="w-8 h-8 text-purple-600 mb-3" />
          <p className="text-sm font-medium text-gray-700 mb-4">
            Scan QR Code with InstaPay
          </p>
          
          {qrCodeUrl && (
            <div className="bg-white p-4 rounded-lg border-2 border-gray-200">
              <img
                src={qrCodeUrl}
                alt="InstaPay QR Code"
                className="w-64 h-64"
              />
            </div>
          )}
          
          <p className="text-xs text-gray-500 mt-4">
            QR Code valid for 30 minutes
          </p>
        </div>
      </div>

      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
        <div className="flex items-start gap-2">
          <CheckCircle className="w-5 h-5 text-blue-600 mt-0.5 flex-shrink-0" />
          <div className="text-sm text-blue-700">
            <p className="font-medium mb-1">Instant Confirmation</p>
            <p>Your order will be confirmed automatically after successful payment. You'll receive a confirmation email immediately.</p>
          </div>
        </div>
      </div>

      <Button
        onClick={onConfirm}
        size="lg"
        className="w-full"
      >
        <Smartphone className="w-4 h-4 mr-2" />
        I've Completed the Payment
      </Button>

      <p className="text-xs text-center text-gray-500">
        Powered by InstaPay • Instant Bank Transfer
      </p>
    </div>
  );
}
